[package]
name = "pronouncer"
version = "0.1.0"
authors = ["CoolOppo <CoolOppo@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bincode = "1.0.1"
pronouncer_lib = {path ="../pronouncer_lib"}
